name: test-sync
on:
  schedule:
    - cron: '14 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-xiaofei-ya-proxypool
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync xiaofei-ya-proxypool
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/xiaofei-ya/proxypool.git"
          source_branch: "heroku"
          destination_branch: "xf001"
          github_token: ${{ secrets.PAT }}
